/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conexao;
import dao.UsuarioDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import model.UsuarioM;
import util.LimiteDigitos;

/**
 *
 * @author Leopo
 */
public class LoginView extends javax.swing.JFrame {

    UsuarioM usuarioM;
    UsuarioDAO usuarioDAO;
    
    public LoginView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        usuarioM = new UsuarioM();
        
        this.tfdUsuario.requestFocus();
        usuarioDAO = new UsuarioDAO();
        
        btnEntrar.setUI(new BasicButtonUI());
        btnConvidado.setUI(new BasicButtonUI());
        
        
        URL url = this.getClass().getResource("/view/icones/icon.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        tfdUsuario.setDocument(new LimiteDigitos(20));
        tfdSenha.setDocument(new LimiteDigitos(20));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        tfdSenha = new javax.swing.JPasswordField();
        tfdUsuario = new javax.swing.JTextField();
        btnConvidado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(165, 214, 168));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(61, 100, 63));
        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        btnEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEntrarKeyPressed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, -1));

        tfdSenha.setBackground(new java.awt.Color(250, 250, 250));
        tfdSenha.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfdSenha.setForeground(new java.awt.Color(29, 29, 29));
        tfdSenha.setToolTipText("Digite sua senha");
        tfdSenha.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfdSenha.setPreferredSize(new java.awt.Dimension(210, 23));
        tfdSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(tfdSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 340, 40));

        tfdUsuario.setBackground(new java.awt.Color(250, 250, 250));
        tfdUsuario.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfdUsuario.setForeground(new java.awt.Color(29, 29, 29));
        tfdUsuario.setToolTipText("Digite seu usuário");
        tfdUsuario.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 226, 226)), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        tfdUsuario.setPreferredSize(new java.awt.Dimension(59, 23));
        tfdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdUsuarioActionPerformed(evt);
            }
        });
        tfdUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdUsuarioKeyPressed(evt);
            }
        });
        jPanel1.add(tfdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 340, 40));

        btnConvidado.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnConvidado.setText("Entrar como convidado");
        btnConvidado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvidadoActionPerformed(evt);
            }
        });
        btnConvidado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnConvidadoKeyPressed(evt);
            }
        });
        jPanel1.add(btnConvidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jPanel2.setBackground(new java.awt.Color(38, 54, 59));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 243, 243));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AGENDA");
        jPanel2.add(jLabel3, "card2");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
      
        usuarioM = null;
        try {
            if (tfdUsuario.getText().isEmpty()) {
                //erro.setText("O nome do usuario deve ser preechido");
                JOptionPane.showMessageDialog(null, "O usuário deve ser preenchido", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                tfdUsuario.requestFocus();

            } else if (tfdSenha.getText().isEmpty()) {
                //erro.setText("A senha deve ser preechido");
                //erro.setVisible(true);
                JOptionPane.showMessageDialog(null, "A senha deve ser preenchida", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                tfdSenha.requestFocus();
            } else {
                usuarioM = UsuarioDAO.valida(tfdUsuario.getText(), tfdSenha.getText());
                if(usuarioM == null){
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                    tfdUsuario.setText("");
                    tfdSenha.setText("");
                    tfdUsuario.requestFocus();
                }else{
       
                    PrincipalView principal = new PrincipalView(usuarioM);
                    this.dispose();
                    
                }
                
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
            tfdUsuario.setText("");
            tfdSenha.setText("");
            tfdUsuario.requestFocus();
            ex.printStackTrace();
            
        }
        this.dispose();
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void tfdUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfdSenha.requestFocusInWindow();
        }        
    }//GEN-LAST:event_tfdUsuarioKeyPressed

    private void btnConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvidadoActionPerformed
    UsuarioM usuarioM = new UsuarioM();
    usuarioM = null;
    String convidado = "convidado";
    try{
        usuarioM = UsuarioDAO.valida(convidado, convidado);
    }
    catch(Exception ex){
        ex.printStackTrace();
    }
    PrincipalView principal = new PrincipalView(usuarioM);
    this.dispose();
    }//GEN-LAST:event_btnConvidadoActionPerformed

    private void tfdSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdSenhaKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            usuarioM = null;
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (tfdUsuario.getText().isEmpty()) {
                   // erro.setText("O nome do usuario deve ser preechido");
                   // erro.setVisible(true);
                   JOptionPane.showMessageDialog(null, "O usuário deve ser preenchido", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                    tfdUsuario.requestFocus();
                } else if (tfdSenha.getText().isEmpty()) {
                   // erro.setText("A senha deve ser preechida");
                   // erro.setVisible(true);
                   JOptionPane.showMessageDialog(null, "A senha deve ser preenchida", "Alerta", JOptionPane.INFORMATION_MESSAGE);
                    tfdSenha.requestFocus();
                } else {
                    usuarioM = usuarioDAO.valida(tfdUsuario.getText(), tfdSenha.getText());
                    if(usuarioM == null){
                        JOptionPane.showMessageDialog(null, "Usuário não encontrado", "Erro", JOptionPane.ERROR_MESSAGE);
                        tfdUsuario.setText("");
                        tfdSenha.setText("");
                        tfdUsuario.requestFocus();
                    }else{
                        PrincipalView pv = new PrincipalView(usuarioM);
                        this.dispose();
                    }
                    
                    
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorreto", "Erro", JOptionPane.ERROR_MESSAGE);
                tfdUsuario.setText("");
                tfdSenha.setText("");
                tfdUsuario.requestFocus();

            }
        }
        }
    }//GEN-LAST:event_tfdSenhaKeyPressed

    private void btnConvidadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvidadoKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
    PrincipalView principal = new PrincipalView(usuarioM);
        }
    }//GEN-LAST:event_btnConvidadoKeyPressed

    private void btnEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEntrarKeyPressed
     
    }//GEN-LAST:event_btnEntrarKeyPressed

    private void tfdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdUsuarioActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvidado;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField tfdSenha;
    private javax.swing.JTextField tfdUsuario;
    // End of variables declaration//GEN-END:variables
}
